@url = https://localhost:44385

###komentarz
GET {{url}}/weatherforecast HTTP/1.1

###komentarz
GET {{url}}/customers HTTP/1.1

###komentarz
POST {{url}}/statistics
Content-Type: application/json 

{
    "FullCalculation": "true",
}

###komentarz
GET {{url}}/customers/newest?limit=100 HTTP/1.1

###komentarz
POST {{url}}/orders
Content-Type: application/json 

{
    "CustomerId": "BLAUS",
    "Products":
    [
        { 
            "ProductId" : 1,
            "Quantity" : 10
        },
        { 
            "ProductId" : 76,
            "Quantity" : 10
        }

    ]
}

###komentarz

POST {{url}}/login
Content-Type: application/json 

{
    "userName": "test2@test.com",
    "password": "password2"
}

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQHRlc3QuY29tIiwicm9sZSI6InVzZXIiLCJuYmYiOjE2MTYxNTk1MTEsImV4cCI6MTYxNjI0NTkxMSwiaWF0IjoxNjE2MTU5NTExLCJpc3MiOiJub3J0aHdpbmRBUEkiLCJhdWQiOiJub3J0aHdpbmRDbGllbnQifQ.Z3w062n8nPeiUZtyO_96tlPiAE88mMOK7SwBEaK2EZI
###komentarz
GET {{url}}/weatherforecast
Authorization: bearer {{token}}

###komentarz
GET {{url}}/weatherforecast/get2
Authorization: bearer {{token}}

